Algoritmo "contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/04/2026
Var
   contador:Inteiro

Inicio
      contador <- 100
      Enquanto (contador >=0)faca
          Escreva(contador)
          //contador <- contador -1
          contador <- contador -2
      FimEnquanto


Fimalgoritmo