Algoritmo "contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/04/2026
Var
   contador:Inteiro

Inicio
      contador <- 0
      Enquanto (contador <= 10)faca
          Escreval(contador)
          contador <- contador +1
      FimEnquanto


Fimalgoritmo