Algoritmo "contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/04/2026
Var
   valor,contador,salto:Inteiro

Inicio
      contador <- 0
      Escreva("Quer quantos passos? ")
      Leia(valor)
      Escreva("Qual será o valor do salto? ")
      Leia(salto)
      Enquanto (contador <= valor)faca
          Escreva(contador)
          contador <- contador + salto
      FimEnquanto


Fimalgoritmo